# This is the build file for djengu itself.
# You should remove it, and use the deploy-prod
# file to set up your github actions.

name: test-build

on:
  push:
    branches:
      - main


jobs:

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run build
        run: sudo apt-get update -y && sudo apt-get install python3-virtualenv -y && make test-build
